---
title: "Results"
output: 
    github_document:
       df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(drake)
library(ggplot2)
library(dplyr)
source(here::here("crossval_fxns.R"))
source(here::here("more_fxns.R"))

## Set up the cache and config
db <- DBI::dbConnect(RSQLite::SQLite(), here::here("analysis", "drake", "drake-cache.sqlite"))
cache <- storr::storr_dbi("datatable", "keystable", db)
cache$del(key = "lock", namespace = "session")
```

```{r load dat}

loadd(bbs_rtrg_1_11, cache = cache)

totaln <- bbs_rtrg_1_11$abundance %>%
  mutate(totaln = rowSums(.)) %>%
  mutate(year = bbs_rtrg_1_11$covariates$year)

abund_long <- totaln %>%
  select(-totaln) %>%
  tidyr::pivot_longer(-year, names_to = "species", values_to = "count") %>%
  left_join(select(totaln, year, totaln)) %>%
  mutate(prop = count / totaln)

ggplot(abund_long, aes(year, prop, color = species)) +
  geom_line() +
  theme_bw() +
  scale_color_viridis_d() +
  theme(legend.position = "none")


```

```{r}

all_evals <- read.csv(here::here("all_evals_bbs_rtrg_1_11.csv"))
all_evals <- all_evals %>%
  mutate(k = as.factor(k),
         seed = as.factor(seed),
         cpts = as.factor(cpts),
         cpts_seed_k = paste0(cpts, "_", seed, "_", k),
         cpts_k = paste0(k, "_", cpts))


# ggplot(all_evals, aes(x = k, y = loglik, group = cpts_seed_k, color = cpts)) +
#   geom_jitter(width = 0, alpha = .01) +
# #  facet_wrap(vars(cpts)) +
#   theme_bw() +
#   ggtitle("All models loglikelihood")

all_evals_summary <- all_evals %>%
  group_by(k, seed, cpts, cpts_seed_k, cpts_k, mean_loglik) %>%
  summarize(mean_ll = mean(loglik, na.rm = T),
            upper_97_ll = quantile(loglik, probs = .975, na.rm= T),
            lower_2_ll = quantile(loglik, probs = .025, na.rm =T),
            n_infinite = sum(is.infinite(loglik)),
            n_na = sum(is.na(loglik))) %>%
  ungroup() %>%
  arrange(desc(mean_loglik)) %>%
  mutate(se = sd(mean_loglik) / sqrt(length(unique(cpts_seed_k)))) 

max_ll <- max(all_evals_summary$mean_loglik)

all_evals_summary$near_max <- all_evals_summary$mean_loglik >= max_ll - all_evals_summary$se[1]

ggplot(all_evals_summary, aes(x = cpts, y = mean_loglik, color = cpts)) +
  geom_point() +
facet_wrap(vars(k), nrow = 1) +
  theme_bw() +
  ggtitle("All models loglikelihood")

highest_low_95 = max(all_evals_summary$lower_2_ll)

all_evals_summary <- all_evals_summary %>%
  mutate(in_95 = upper_97_ll >= highest_low_95)

head(all_evals_summary)

all_evals_summary[1:15,]

ggplot(filter(all_evals, cpts_seed_k %in% all_evals_summary$cpts_seed_k[1:25]), aes(x = k, y = loglik, group = cpts_seed_k, color = cpts)) +
  geom_boxplot() +
#  facet_wrap(vars(cpts)) +
  theme_bw() +
  ggtitle("Best 25 models loglikelihood")


ggplot(filter(all_evals, cpts_seed_k %in% filter(all_evals_summary, in_95)$cpts_seed_k), aes(x = k, y = loglik, group = cpts_seed_k, color = cpts)) +
  geom_boxplot() +
#  facet_wrap(vars(cpts)) +
  theme_bw() +
  ggtitle("Models w/LL overlapping top 95%")
# 
# some_ldas <- LDATS::LDA_set_user_seeds(bbs_rtrg_1_11$abundance, topics = c(2:5), seed = 2)
# 
# for(i in 1:length(some_ldas)) {
#   print(plot_lda_year(some_ldas[[i]], covariate_data = bbs_rtrg_1_11$covariates$year))
# }
```

# ```{r}
#  loadd(ldats_fit_bbs_rtrg_1_11_2_2_1L, cache = cache)
# loadd(ldats_eval_ldats_fit_bbs_rtrg_1_11_2_2_1L, cache = cache)
# 
# lls <- lapply(ldats_fit_bbs_rtrg_1_11_2_2_1L, FUN = function(alist)
#   return(data.frame(ll = alist$test_logliks, timestep = alist$test_timestep)))
# names(lls) <- 1:length(lls)
# 
# lls <- bind_rows(lls)
# 
# lls <- lls %>%
#   group_by(timestep) %>%
#   mutate(ts_mean = mean(ll))
# 
# lls_mean <- lls  %>%
#   select(timestep, ts_mean) %>%
#   distinct() %>%
#   select(ts_mean) 
# 
# ggplot(lls, aes(timestep, ll, group = timestep)) +geom_boxplot() + geom_point(aes(timestep, ts_mean), color = "green") +
#   geom_hline(yintercept = mean(lls_mean$ts_mean), color = "pink")
# 
# 
# ggplot(ldats_eval_ldats_fit_bbs_rtrg_1_11_2_2_1L, aes(x = 1, y = loglik)) +
#   geom_boxplot() +
#   geom_hline(yintercept = mean(lls_mean$ts_mean) * 23, color = "pink")
# 
# ```

<!-- ```{r random ts on lda} -->
<!-- an_lda <- LDATS::LDA_set_user_seeds(bbs_rtrg_1_11$abundance, 2, 1) -->
<!-- a_ts <- LDATS::TS_on_LDA(an_lda, as.data.frame(bbs_rtrg_1_11$covariates), formulas = ~ 1, nchangepoints = c(0:3), timename = "year", control = LDATS::TS_control(nit = 100)) -->

<!-- ts_lls <- lapply(a_ts, FUN = function(a_ts_fit) return(data.frame(cpts = a_ts_fit$nchangepoints, ll = a_ts_fit$lls))) -->

<!-- ts_lls <- bind_rows(ts_lls) -->

<!-- ts_lls <- ts_lls %>% -->
<!--   group_by(cpts) %>% -->
<!--   mutate(mean_ll = mean(ll), -->
<!--             bottom2 = quantile(ll, probs = .025), -->
<!--             top97 = quantile(ll, probs = .975)) %>% -->
<!--   ungroup() -->

<!-- ggplot(ts_lls, aes(x = cpts, y = ll, group = cpts)) + -->
<!--   geom_boxplot() + -->
<!--   geom_point(aes(cpts, bottom2), color = "red") + -->
<!--   geom_point(aes(cpts, top97), color = "red") + -->
<!--   geom_point(aes(cpts, mean_ll), color = "green") -->

<!-- ``` -->

<!-- So you do see, spread causing overlapping 95% intervals for the loglikelihoods for models that we would distinguish between using AIC. -->

<!-- In this case I'm not confident using AIC or AICc for final selection because the models are not fit to the same data. -->

<!-- However you could fit *another* TS model to the *full* ts to see if that lands you somewhere other than the highest mean ll on the crossval.  -->

```{r}
load(here::here("fit.RData"))

for(i in 1:length(ldats_fit_bbs_rtrg_1_11_3L_8_3L)) {
  if(anyNA(ldats_fit_bbs_rtrg_1_11_3L_8_3L[[i]]$test_logliks)) {
    print(i)
  }
  if(length(ldats_fit_bbs_rtrg_1_11_3L_8_3L[[i]]$test_logliks) < 1000) {
    print(i)
    print(length(ldats_fit_bbs_rtrg_1_11_3L_8_3L[[i]]$test_logliks))
  }
}

load(here::here("eval.RData"))

```


## Getting back to a single model 

The best-fit from the ones run so far is 3 changepoints, 3 topics, seed = 8. 

```{r}
# 
# loadd(ldats_fit_bbs_rtrg_1_11_3L_4_2L, cache= cache)
# loadd(ldats_eval_ldats_fit_bbs_rtrg_1_11_3L_4_2L, cache= cache)

full_lda <- LDATS::LDA_set_user_seeds(ldats_fit_bbs_rtrg_1_11_3L_8_3L[[1]]$full$abundance, 3, 8)

plot_lda_comp(full_lda)

plot_lda_year(full_lda, covariate_data = ldats_fit_bbs_rtrg_1_11_3L_8_3L[[1]]$full$covariates$year)

full_ts <- LDATS::TS_on_LDA(full_lda, as.data.frame(ldats_fit_bbs_rtrg_1_11_3L_8_3L[[1]]$full$covariates), ~1, 3, "year", control=LDATS::TS_control(nit=100))


full_ts2 <- LDATS::TS_on_LDA(full_lda, as.data.frame(ldats_fit_bbs_rtrg_1_11_3L_8_3L[[1]]$full$covariates), ~1, 2, "year", control=LDATS::TS_control(nit=100))
```

```{r}

full_rhos <- full_ts[[1]]$rhos

subset_rhos <- lapply(ldats_fit_bbs_rtrg_1_11_3L_8_3L, FUN = function(ldats_fit) return(cbind(ldats_fit$fitted_ts$rhos, ldats_fit$test$covariates$year[1])))

subset_rhos <- lapply(subset_rhos, FUN = function(s_r) return(as.data.frame(s_r)))

names(subset_rhos) <- 1:length(subset_rhos)

subset_rhos <- bind_rows(subset_rhos)

subset_rhos <- subset_rhos %>%
  rename(r1 = V1,
         r2 = V2,
         r3 = V3,
         testyear = V4) %>%
  tidyr::pivot_longer(-testyear, names_to = "cpt", values_to = "est") %>%
  mutate(source = "subset")


full_rhos <- as.data.frame(full_rhos) %>%
  rename(r1 = V1,
         r2 = V2,
         r3 = V3) %>%
  mutate(source = "full") %>%
  tidyr::pivot_longer(-source, names_to = "cpt", values_to = "est") %>%
  mutate(testyear = NA)


all_rhos <- rbind(full_rhos, subset_rhos)

ggplot(all_rhos, aes(est)) +
  geom_histogram() +
  facet_grid(rows = vars(source), cols = vars(cpt), scales = "free_y") 

all_rhos %>%
  group_by(source, cpt) %>%
  summarize(mean_est = mean(est))

```

In this case, if we take all the rho estimates across the subsetted models and compare them to the rho estimates from a single TS fit to the full TS, we get the same estimates for rho. 

```{r full ts pred}


full_preds <- lapply(1:100, FUN = get_preds, subsetted_dataset_item = ldats_fit_bbs_rtrg_1_11_3L_8_3L[[1]], fitted_ts = full_ts[[1]])

full_preds <- bind_rows(full_preds)

full_preds$topic_est <- paste0(full_preds$topic, full_preds$estimate)

ggplot(full_preds, aes(year, prop, color= topic, group = topic_est)) +
  geom_line(alpha = .012)


rho_preds <- get_preds(subsetted_dataset_item = ldats_fit_bbs_rtrg_1_11_3L_8_3L[[1]], fitted_ts = full_ts[[1]], rho = c(1983, 1994, 2005))


ggplot(rho_preds, aes(year, prop, color= topic, group = topic)) +
  geom_line() +
  theme_bw()

```

```{r close connection}

DBI::dbDisconnect(db)
rm(cache)

```