---
title: "Portal rats + Hartland birds"
author: Renata Diaz
date: "`r Sys.Date()`"
output: 
    github_document:
       df_print: kable
       toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(ggplot2)
library(LDATS)
library(cvlt)
library(drake)

## Set up the cache and config
db <- DBI::dbConnect(RSQLite::SQLite(), here::here("analysis", "drake", "drake-cache-cvlt.sqlite"))
cache <- storr::storr_dbi("datatable", "keystable", db)
cache$del(key = "lock", namespace = "session")

theme_set(theme_bw())

```
## Specs

```{r, echo = T, eval = F}
 ldats_fit = target(fit_ldats_crossval(dataset, buffer = 2, k = ks, lda_seed = seeds, cpts = cpts, nit = 100),
                       transform = cross(
                         dataset = !!rlang::syms(datasets$target),
                         ks = !!c(0,2:3),
                         seeds = !!seq(2, 10, by = 2),
                         cpts = !!c(0:4),
                         return_full = F,
                         return_fits = F,
                         summarize_ll = F
                       ))
)
```


```{r}

loadd(all_dataset_fits_portal_annual, cache = cache)
loadd(all_dataset_fits_bbs_rtrg_102_18, cache = cache)

bbs_best <- filter(all_dataset_fits_bbs_rtrg_102_18, mean_loglik == max(all_dataset_fits_bbs_rtrg_102_18$mean_loglik)) %>%
  mutate(min_within = mean_loglik - se_loglik) %>%
  select(dat_name, min_within)

portal_best <- filter(all_dataset_fits_portal_annual, mean_loglik == max(all_dataset_fits_portal_annual$mean_loglik)) %>%
  mutate(min_within = mean_loglik - se_loglik) %>%
  select(dat_name, min_within)

best_lls <- bind_rows(bbs_best, portal_best)

all_dataset_fits <- bind_rows(all_dataset_fits_portal_annual, all_dataset_fits_bbs_rtrg_102_18) %>%
  left_join(best_lls) %>%
  mutate(is_within = mean_loglik > min_within)


ggplot(all_dataset_fits, aes(k, mean_loglik, color  = is_within)) +
  geom_point() +
  geom_hline(aes(yintercept = min_within)) +
  facet_grid(cols = vars(cpts), rows = vars(dat_name), scales = "free_y")

```

## BBS

```{r}

loadd(best_mod_dataset_best_config_all_dataset_fits_bbs_rtrg_102_18, cache = cache)

bbs_summ <- summarize_model(best_mod_dataset_best_config_all_dataset_fits_bbs_rtrg_102_18)

bbs_summ

plot(best_mod_dataset_best_config_all_dataset_fits_bbs_rtrg_102_18$lda_mod)
plot(best_mod_dataset_best_config_all_dataset_fits_bbs_rtrg_102_18$ts_mod, selection = "mode")

```

## Portal


```{r}

loadd(best_mod_dataset_best_config_all_dataset_fits_portal_annual, cache = cache)

portal_summ <- summarize_model(best_mod_dataset_best_config_all_dataset_fits_portal_annual)

portal_summ

plot(best_mod_dataset_best_config_all_dataset_fits_portal_annual$lda_mod)
plot(best_mod_dataset_best_config_all_dataset_fits_portal_annual$ts_mod, selection = "mode")

```