---
title: "CTM"
output: github_document
---

```{r setup, include=FALSE}

library(dplyr)
library(topicmodels)
library(ggplot2)
source(here::here("fxns", "lda_wrapper.R"))

```

# directional changepoint data

```{r everything}

directional_changepoint <- read.csv(here::here("data", "directional_changepoint.csv"), stringsAsFactors = F)

abund_mat <- directional_changepoint %>%
  as.data.frame() %>%
  mutate(year = row_number()) %>%
  tidyr::gather(-year, key = "species", value = "abundance") %>%
  group_by(year) %>%
  mutate(total_abund = sum(abundance)) %>%
  ungroup() %>%
  mutate(rel_abund = abundance / total_abund)

true_ts <- ggplot(data = abund_mat, aes(x = year, y = rel_abund, color = species)) +
  geom_line() +
  theme_bw() +
  theme(legend.position = "none") +
  scale_color_viridis_d() +
  ggtitle("Real TS data")+
  ylim(0,1)

true_ts

directional_changepoint <- as.matrix(directional_changepoint)


CTM_2 <- CTM(directional_changepoint, 3, control = list(seed = 4))
CTM_2@beta

LDA_2 <- LDA(directional_changepoint,3, control = list(seed = 4))
LDA_2@beta

ctm_gammas <- CTM_2@gamma %>%
  as.data.frame() %>%
  mutate(timestep = row_number()) %>%
  tidyr::gather(-timestep, key = "topic", value = "gamma")

ggplot(data = ctm_gammas, aes(x = timestep, y = gamma, color = topic)) + 
  geom_line() +
  ggtitle("CTM gammas") + 
  theme_bw()


lda_gammas <- LDA_2@gamma %>%
  as.data.frame() %>%
  mutate(timestep = row_number()) %>%
  tidyr::gather(-timestep, key = "topic", value = "gamma")

ggplot(data = lda_gammas, aes(x = timestep, y = gamma, color = topic)) + 
  geom_line() +
  ggtitle("LDA gammas") + theme_bw()


plot(LDATS::LDA_set_user_seeds(directional_changepoint, 3, 4))

```
```{r ts model}

dc <- get_sim_dat("directional_changepoint")

LDA_CTM <- LDA_2
LDA_CTM@gamma <- CTM_2@gamma
LDA_CTM@beta <- CTM_2@beta

library(LDATS)
plot(LDA_CTM)

CTM_TS <- TS_on_LDA(LDA_CTM, document_covariate_table = dc$covariates, formulas =  c(~timestep, ~1), nchangepoints = c(0, 1), weights = document_weights(dc$abundance), timename = "timestep")

for(i in 1:length(CTM_TS)) {
  print(names(CTM_TS)[[i]])
  plot(CTM_TS[[i]])
}
```

```{r selected ctm}
selected_ctm <- (LDATS::select_TS(CTM_TS))

print(selected_ctm$formula)
print(selected_ctm$nchangepoints)

plot(selected_ctm)
```

```{r compared to on LDA}

LDA2_TS <- TS_on_LDA(LDA_2, document_covariate_table = dc$covariates, formulas =  c(~timestep, ~1), nchangepoints = c(0, 1), weights = document_weights(dc$abundance), timename = "timestep")

for(i in 1:length(LDA2_TS)) {
  print(names(LDA2_TS)[[i]])
  plot(LDA2_TS[[i]])
}

selected_lda <- (LDATS::select_TS(LDA2_TS))

print(selected_lda$formula)
print(selected_lda$nchangepoints)

plot(selected_lda)
```